### ISSUE TITLE
Variable vibration intensity from vibrotactors during session

### ISSUE THREAD

**Issue by JamesEPierce** [Munroe-Meyer-Institute-VR-Laboratory/cometrics#32]
During walking/standing sessions, the motors in the vibrotactors were very noticeably increasing in intensity and returning to the set value. This happened intermittently, was very sudden, and would cycle in/out in somewhat regular intervals after starting. 

The severity of the vibration fluctuations also dropped significantly when the lab's all-in-one PC was turned to face the treadmill, but didn't go away completely. Maybe it's related to Bluetooth range? It was verified during calibration after the issue occurred that the vibrotactors' intensity was higher than at the session start as well, with the right foot being noticeable at a threshold of 20/255 even with a 50 Ohm resistor connected to it.

Log file is pasted below:

STARTUP: Wed Aug  3 12:12:10 2022
STARTUP: Manufacturer - Dell Inc.
STARTUP: Model - OptiPlex 7450 AIO
STARTUP: Name - MMIATPC2
STARTUP: NumberOfProcessors - 1
STARTUP: SystemType - x64-based PC
STARTUP: SystemFamily - OptiPlex
STARTUP: Physical Memory Total - 15.70GB
STARTUP: Physical Memory Available - 8.22GB
STARTUP: Physical Memory Used - 7.48GB
STARTUP: Physical Memory Percentage - 47.6%
STARTUP: Swap Memory Total - 2.38GB
STARTUP: Swap Memory Free - 1.42GB
STARTUP: Swap Memory Used - 976.10MB
STARTUP: Swap Memory Percentage - 40.1%
STARTUP: C:\Users\gaitlab\AppData\Local\Programs\cometrics\1.3.0
INFO: imageio_ffmpeg exe location - C:\Users\gaitlab\AppData\Local\Programs\cometrics\1.3.0\external_bin\ffmpeg\ffmpeg-win64-v4.2.2.exe
INFO: C:\Users\gaitlab\AppData\Local\Programs\cometrics\1.3.0\external_bin\ffmpeg\ffmpeg-win64-v4.2.2.exe
INFO: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\S02.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\KSF\Vibrotactor KSF_7-26-2022.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Reliability
INFO: ('Purisa', 16) ('Purisa', 14) 70 1920 1080
INFO: Thresholds ['', '', '']
No handles with labels found to put in legend.
No handles with labels found to put in legend.
No handles with labels found to put in legend.
INFO: Vibrotactors not calibrated!
INFO: Woodway is not calibrated!
INFO: Number of fields: 10
INFO: Number of frames: 3
INFO: Vibrotactor array connected!
INFO: Vibrotactor array connected!
INFO: VTA Left - VibrotactorArraySide.RIGHT VTA Right - VibrotactorArraySide.LEFT
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: Disconnected from vibrotactor: <adafruit_ble.BLEConnection object at 0x000001A9CF6B6AC0>
INFO: Disconnected from vibrotactor: <adafruit_ble.BLEConnection object at 0x000001A9CF6D1610>
INFO: Saved session file to: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary\115_1_0811Aug032022.json
INFO: Wed Aug  3 14:29:47 2022
INFO: Process Memory - 273.44 MB
INFO: RAM Usage - 47.9%
INFO: Physical Memory Used - 7.52GB
INFO: Physical Memory Percentage - 47.9%
INFO: Swap Memory Used - 1019.12MB
INFO: Swap Memory Percentage - 41.9%
INFO: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\S02.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\KSF\Vibrotactor KSF_7-26-2022.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Reliability
INFO: ('Purisa', 16) ('Purisa', 14) 70 1920 1080
INFO: Thresholds [70, 148, 1.6749999999999998]
No handles with labels found to put in legend.
No handles with labels found to put in legend.
No handles with labels found to put in legend.
INFO: Vibrotactors already calibrated - Right: 70 Left: 148 Calibrated: True
INFO: Woodway calibrated already - Thresh: 1.6749999999999998 Calibrated: True
INFO: Number of fields: 10
INFO: Number of frames: 3
INFO: Loading primary data session 1
INFO: Vibrotactor array connected!
INFO: Vibrotactor array connected!
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: Disconnected from vibrotactor: <adafruit_ble.BLEConnection object at 0x000001A9D309C880>
INFO: Disconnected from vibrotactor: <adafruit_ble.BLEConnection object at 0x000001A9D3052C10>
INFO: Saved session file to: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary\100_2_0810Aug032022.json
INFO: Wed Aug  3 14:42:40 2022
INFO: Process Memory - 302.44 MB
INFO: RAM Usage - 48.7%
INFO: Physical Memory Used - 7.65GB
INFO: Physical Memory Percentage - 48.7%
INFO: Swap Memory Used - 1.03GB
INFO: Swap Memory Percentage - 43.2%
INFO: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\S02.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\KSF\Vibrotactor KSF_7-26-2022.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Reliability
INFO: ('Purisa', 16) ('Purisa', 14) 70 1920 1080
INFO: Thresholds [70, 148, 1.6749999999999998]
No handles with labels found to put in legend.
No handles with labels found to put in legend.
No handles with labels found to put in legend.
INFO: Vibrotactors already calibrated - Right: 70 Left: 148 Calibrated: True
INFO: Woodway calibrated already - Thresh: 1.6749999999999998 Calibrated: True
INFO: Number of fields: 10
INFO: Number of frames: 3
INFO: Vibrotactor array connected!
INFO: Vibrotactor array connected!
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: No key events returned
INFO: Disconnected from vibrotactor: <adafruit_ble.BLEConnection object at 0x000001A9D39B8820>
INFO: Disconnected from vibrotactor: <adafruit_ble.BLEConnection object at 0x000001A9D3A1F550>
INFO: Saved session file to: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary\85_3_0885Aug032022.json
INFO: Wed Aug  3 14:57:32 2022
INFO: Process Memory - 320.09 MB
INFO: RAM Usage - 48.7%
INFO: Physical Memory Used - 7.64GB
INFO: Physical Memory Percentage - 48.7%
INFO: Swap Memory Used - 1.01GB
INFO: Swap Memory Percentage - 42.5%
INFO: C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\S02.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\KSF\Vibrotactor KSF_7-26-2022.json C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Primary C:\cometrics\1.1.4\Projects\OneDrive - University of Nebraska Medical Center\Vibrotactor Project 1 (IRB#0800-21-EP)\Adult Neurotypical\S02\Data Collection Assessment\Raw Data\Reliability
INFO: ('Purisa', 16) ('Purisa', 14) 70 1920 1080
INFO: Thresholds [70, 148, 1.6749999999999998]
No handles with labels found to put in legend.
No handles with labels found to put in legend.
No handles with labels found to put in legend.
INFO: Vibrotactors already calibrated - Right: 70 Left: 148 Calibrated: True
INFO: Woodway calibrated already - Thresh: 1.6749999999999998 Calibrated: True
INFO: Number of fields: 10
INFO: Number of frames: 3
INFO: Vibrotactor array connected!
INFO: Vibrotactor array connected!
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT
INFO: VTA Left - VibrotactorArraySide.LEFT VTA Right - VibrotactorArraySide.RIGHT

**Comment by wsarce** [comment]
This has been determined to be an issue with the Bluetooth device battery and not an issue with cometrics.  Closing for now.
